remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: "false"
google_analytics: UA-145694449-1
title: 快翻墙
description: 持续关注在中国还能用的翻墙VPN排行榜，测评快速稳定的翻墙软件，涵盖电脑以及苹果安卓手机，为中国VPN用户推荐好用的VPN。
